repos:
  - repo: local
    hooks:
      - id: cargo-check
        name: Cargo check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-fmt-check
        name: Cargo fmt check
        entry: cargo fmt -- --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: Cargo clippy
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false