app = "zzstoatzz-status"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  DB_PATH = "/data/status.db"
  ENABLE_FIREHOSE = "true"
  # PUBLIC_URL will be set dynamically by the workflow

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[mounts]]
  source = "status_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256